apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: hello-user-rs
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-user
  template:
    metadata:
      labels:
        app: hello-user
    spec:
      containers:
      - image: etlars/node_user:v2
        name: hello-user
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-user-svc
  namespace: ingress-nginx
spec:
  selector:
    app: hello-user
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  #type: LoadBalancer
  type: NodePort
