apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    type: web
  name: test-rc
spec:
  replicas: 2
  selector:
    type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - image: zlabjp/docker-example:release-0.1.0
        name: test-container
        ports:
        - containerPort: 4000

