apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    type: web2
  name: test-rc2
  namespace: default
spec:
  replicas: 2
  selector:
    type: web2
  template:
    metadata:
      labels:
        type: web2
    spec:
      containers:
      - image: etlars/node_user:v1
        name: test-container
        ports:
        - containerPort: 8080
