apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs-product
  labels:
    type: web2
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web2
  template:
    metadata:
      labels:
        type: web2
    spec:
      containers:
      - name: test-container-product
        image: etlars/node_product:v2
        ports:
        - containerPort: 8080
