apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs-root
  namespace: other
  labels:
    type: web0-other
spec:
  replicas: 1
  selector:
    matchLabels:
      type: web0-other
  template:
    metadata:
      labels:
        type: web0-other
    spec:
      containers:
      - name: test-container0-other
        image: etlars/nodejs_server:v2
        ports:
        - containerPort: 8080
