apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs-user
  labels:
    type: web
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: test-container-user
        image: etlars/node_user:v2
        ports:
        - containerPort: 8080
