apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs111
  labels:
    type: web111
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web111
  template:
    metadata:
      labels:
        type: web111
    spec:
      containers:
      - name: test-container111
        image: etlars/node_product:v2
        ports:
        - containerPort: 8080
