apiVersion: v1
kind: Service
metadata:
  name: test-svc3
  labels:
    type: web
spec:
  selector:
    type: web
  ports:
  - port: 80
    targetPort: 4000

--- 
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc3
  labels:
    type: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: test-container3
        image: zlabjp/docker-example:release-0.1.0
        ports:
        - containerPort: 4000
